In [153]:
#!/usr/bin/env python
import tensornetwork as tn
import numpy as np

In [154]:
N = 5
D = 3
p = 2
k = 3

In [155]:
#создаем Node с локальным оператором, который будем вставлять между двух MPSов
operator = tn.Node(np.array([[7,9],[8,-5]]))
print(operator.tensor)

[[ 7  9]
 [ 8 -5]]


In [156]:
#создаем проект первого MPS - массив Node-ов
a=[]
a.append(tn.Node(np.ones((p,D))))
for i in range(1,N-1):
    a.append(tn.Node(np.ones((p,D,D))))
a.append(tn.Node(np.ones((p,D))))
for i in range(N):
    print(a[i].tensor)
    print('$')

[[1. 1. 1.]
 [1. 1. 1.]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[1. 1. 1.]
 [1. 1. 1.]]
$


In [157]:
#соединяем Nodes в цепочку
a[0][1] ^ a[1][1]
for i in range (1,N-1):
    a[i][2] ^ a[i+1][1]

In [158]:
#создаем проект второго MPS
b=[]
b.append(tn.Node(np.ones((p,D))))
for i in range(1,N-1):
    b.append(tn.Node(np.ones((p,D,D))))
b.append(tn.Node(np.ones((p,D))))
for i in range(N):
    print(b[i].tensor)
    print('$')

[[1. 1. 1.]
 [1. 1. 1.]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[1. 1. 1.]
 [1. 1. 1.]]
$


In [159]:
#соединяем Nodes в цепочку
b[0][1] ^ b[1][1]
for i in range (1,N-1):
    b[i][2] ^ b[i+1][1]

In [160]:
#попарно сшиваем Nodes двух цепочек (в нужном месте вставляем operator), получаем одну цепочку
c=[]
for i in range(5):
    if i!=k:
        c.append(tn.contract(a[i][0] ^ b[i][0]))
    else:
        a[i][0] ^ operator[0]
        b[i][0] ^ operator[1]
        x = a[i] @ operator @ b[i]
        print(x.tensor)
        c.append(x)

[[[[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]

  [[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]

  [[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]]


 [[[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]

  [[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]

  [[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]]


 [[[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]

  [[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]

  [[19. 19. 19.]
   [19. 19. 19.]
   [19. 19. 19.]]]]


In [161]:
#схлопываем всю цепочку в скаляр
d = c[0]
for i in range(1,N):
    d = d @ c[i]

In [162]:
print(d.tensor)

1994544.0
