In [45]:
#!/usr/bin/env python
import tensornetwork as tn
import numpy as np

In [46]:
N = 5
D = 3
p = 2

In [47]:
#создаем Nodes в массиве (проект первого MPS)
a=[]
a.append(tn.Node(np.ones((p,D))))
for i in range(1,N-1):
    a.append(tn.Node(np.ones((p,D,D))))
a.append(tn.Node(np.ones((p,D))))
for i in range(N):
    print(a[i].tensor)
    print('$')

[[1. 1. 1.]
 [1. 1. 1.]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[1. 1. 1.]
 [1. 1. 1.]]
$


In [48]:
#соединяем Nodes в цепочку, получаем MPS
a[0][1] ^ a[1][1]
for i in range (1,N-1):
    a[i][2] ^ a[i+1][1]

In [49]:
#создаем аналогично второй MPS
b=[]
b.append(tn.Node(np.ones((p,D))))
for i in range(1,N-1):
    b.append(tn.Node(np.ones((p,D,D))))
b.append(tn.Node(np.ones((p,D))))
for i in range(N):
    print(b[i].tensor)
    print('$')

[[1. 1. 1.]
 [1. 1. 1.]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
$
[[1. 1. 1.]
 [1. 1. 1.]]
$


In [50]:
#соединяем Nodes в цепочку, получаем второй MPS
b[0][1] ^ b[1][1]
for i in range (1,N-1):
    b[i][2] ^ b[i+1][1]

In [51]:
#сшиваем попарно Nodes из a и из b, получаем из двух цепочек одну
c=[]
for i in range(N):
    c.append(tn.contract(a[i][0] ^ b[i][0]))

In [52]:
#схлопываем всю цепочку в 1 скаляр
d = c[0]
for i in range(1,N):
    d = d @ c[i]

In [53]:
print(d.tensor)

209952.0
